server:
  port: 8081
spring:
  application:
    name: book-service

  datasource:
    url: jdbc:mysql://43.138.112.22:3306/springcloud_study
    username: root
    password: zhaoyuyu102
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8888/eureka
