server:
  port: 8888
eureka:
  client:
    fetch-registry: false
#    register-with-eureka: false
    service-url:
#      defaultZone: http://localhost:8889/eureka
      defaultZone: http://eureka01:8889/eureka
  instance:
    hostname: eureka00
spring:
  application:
    name: eurekaServer