server:
  port: 8889
eureka:
  instance:
    hostname: eureka01
  client:
    fetch-registry: false
#    register-with-eureka: false
    service-url:
#      defaultZone: http://localhost:8888/eureka
      defaultZone: http://eureka00:8888/eureka

spring:
  application:
    name: eurekaServer